### PR TITLE
gxui/gxfont: add a fixed-width font

### PR DESCRIPTION
**Pull request by crawshaw**
For some reason I thought the copyright on Droid Sans Mono was held by
another organization, but it appears to be owned by Google. So it makes
an easy inclusion.

The gxfont.a file grows to 100kb with the extra font. This isn't great,
but right now the size is dwarfed by gl/glfw which brings simple
binaries into the 8mb range.

### CODE REVIEW

**Comment by ben-clayton** [comment]
> (ignoring additional size bumps, of course)
Actually, there would not be any increase as the only theme directly pulls in gxfont anyway, which backs the idea more.

**Comment by crawshaw** [comment]
Thanks Ben.

I agree that this technique is effectively baking the fonts into the theme. It's a separate package just because it's conceptually isolated and these default fonts we can ship (thanks to their license) could be used be a "light" theme too.

I'll look at expanding on this script later, but honestly it's so simple I'd rather that someone shipping their own fonts copied it and modified it as necessary. That might change later, as there are a bunch of things in the truetype font not used by freetype-go that we could strip out for compression.

**Comment by ben-clayton** [comment]
SGTM. Thanks.

**Pull request merged**
