### PR TITLE
Allow linear and splitter layouts to have configurable ordering

### PR DESCRIPTION
**Pull request by tones111**
I believe this resolves issue #21

### CODE REVIEW

**Comment by tones111** [comment]
add Direction for these new constants. They're different concepts.

I actually started by defining a direction type, but it adds a bit of additional complexity when validating the direction and orientation against each other.  What should happen if a client sets a horizontal orientation, then TopToBottom direction?  Or they set a LeftToRight direction followed by a vertical orientation.  You end up needing validation logic in both objects.  What do you do in the event of a discrepency?  Do you automatically adjust the other parameter to agree?  What's the point then to having two separate types?  Should an error be returned?  What if the default values for orientation and direction don't agree?

I would actually argue that the the new orientation values are simply less generic versions of horizontal and vertical.  They solve the problem without inducing the complexity above or without the ambiguity of having a "reverse" method that fails to define the normal/default convention.

**Comment by tones111** [comment]
This would still be left / top aligned.

Indeed.  This PR addresses the "We should have an option to reverse the layout order." requirement.  I think there will need to be a bit more work thinking about different layout managers similar to issue #54 and I think that's a separate problem from layout ordering.

**Comment by ben-clayton** [comment]
> I actually started by defining a direction type, but it adds a bit of additional complexity when validating the direction and orientation against each other. What should happen if a client sets a horizontal orientation, then TopToBottom direction? Or they set a LeftToRight direction followed by a vertical orientation. You end up needing validation logic in both objects. What do you do in the event of a discrepency? Do you automatically adjust the other parameter to agree? What's the point then to having two separate types? Should an error be returned? What if the default values for orientation and direction don't agree?

I wasn't actually suggesting keeping the ```SetOrientation``` / ```Orientation``` **methods** on these particular containers - replace them with ```SetDirection``` / ```Direction```.

> I would actually argue that the the new orientation values are simply less generic versions of horizontal and vertical. They solve the problem without inducing the complexity above or without the ambiguity of having a "reverse" method that fails to define the normal/default convention.

I think there's value in having both. Some controls have a Horizontal / Vertical setting that does not have flow direction. For example, I have other controls external to this project that use ```Orientation``` as it is now, so I'd like to keep it. It is very likely I will move these into GXUI in the near future.

> This PR addresses the "We should have an option to reverse the layout order." requirement.

I'm not sure this addresses anything at the moment - it's _almost_ the same behaviour as just adding the controls to the layout in the reverse order (except input handling and tab cycling will prioritise differently). The real goal we're after is the option to layout from right or bottom.

**Comment by tones111** [comment]
I don't think I fully understand what you're looking for with regard to the orientation / direction tweaks.  As mentioned, this PR really doesn't do much, so I recommend closing it.

**Comment by rawkoe1** [comment]
listen bro if u only knew n i only say this cuz ur askin me on what im here
to achieve is a phones capabilityz which are unlocked with vinbes with my
retnas use of no worries of accomplishhion perfection in every angle...

**Comment by ben-clayton** [comment]
@tones111 - [does this give you what you need](https://github.com/google/gxui/pull/64)?

**Comment by tones111** [comment]
I see what you were after now.  I'll play around with it a bit, but the sample really shows off the new functionality well.  One minor thing the demo did illustrate is that there could be some use to implementing the major axis alignment options.  For example TopToBottom with AlignMiddle.  I'll see about adding that.  Thanks.

**Comment by ben-clayton** [comment]
> One minor thing the demo did illustrate is that there could be some use to implementing the major axis alignment options. For example TopToBottom with AlignMiddle. I'll see about adding that. Thanks.

Cool. I agree that having the ```SetHorizontalAlignment``` and ```SetVerticalAlignment``` is confusing given that it only affects the minor axis. So perhaps the API should be to bring back ```SetOrientation``` and use ```SetHorizontalAlignment``` and ```SetVerticalAlignment``` for major and minor axes?

**Pull request closed without merging**
