### PR TITLE
improve MouseButton events

### PR DESCRIPTION
**Pull request by yofu**
Hi @ben-clayton .
This PR will resolve issue #106 .

It's a little bit different from what you answered at the issue, 
but It'd be nice if you could review my code.

Best regards,
yofu

### CODE REVIEW

**Comment by yofu** [comment]
I signed it!

2015年4月21日(火) 14:37 googlebot <notifications@github.com>:

**Comment by yofu** [comment]
Thanks a lot for sparing time for reviewing!

I fixed as below:
* restore all the things associated with MouseButton
* add MouseState instead

I'm not sure whether I fixed well as you mentioned...

I think InputEventHandler.isMouseDown can be gxui.MouseState like:
```golang
func (m *InputEventHandler) MouseDown(ev gxui.MouseEvent) {
	m.isMouseDown = ev.State
	m.getOnMouseDown().Fire(ev)
}
...

func (m *InputEventHandler) IsMouseDown(button gxui.MouseButton) bool {
	return m.isMouseDown.IsDown(button)
}
```

Could you take a look when you have time?

Regards,
yofu

**Comment by yofu** [comment]
Thank you for advice, and I've fixed!

**Comment by ben-clayton** [comment]
LGTM. Thanks!

**Pull request merged**
