### PR TITLE
added screenshots of examples

### PR DESCRIPTION
**Pull request by waynenilsen**
this essentially closes [#93](https://github.com/google/gxui/issues/93).. Actually I added screenshots but did not change the readme.

### CODE REVIEW

**Comment by waynenilsen** [comment]
I signed, I used the github username feature.

**Comment by ben-clayton** [comment]
Thanks for the pull-request @waynenilsen. I'm looking to put these screenshots on a GXUI webpage somewhere as I doubt anyone would actually want to grab these screenshots when they checkout the source.
I'll let you know when that's sorted out.

**Comment by andrewchambers** [comment]
Its possible to just make another repo called gxuiscreenshots then cross reference them in the readme.

**Comment by stiols** [comment]
Or a branch called `screenshots`.

**Comment by Annonomus-Penguin** [comment]
@ben-clayton you can just add them to the README (like this) using Markdown:

    Alt text

Then, they appear in the README

**Comment by stiols** [comment]
> @ben-clayton you can just add them to the README (like this) using
> Markdown:
>
>     Alt text
>
> Then, they appear in the README
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/google/gxui/pull/134#issuecomment-149044262

Did you read what he said? People probably don't want to clone the
screenshot files.

**Comment by waynenilsen** [comment]
How about uploading these to imgur and change the readme to include external links to the images?

**Comment by donatj** [comment]
I generally create an orphan "images" branch for images in Readme,s and what not.

**Pull request closed without merging**
