### PR TITLE
Tree adapter mk2

### PR DESCRIPTION
**Pull request by ben-clayton**
Another attempt at the Tree / TreeAdapter cleanup after [my thoughts on the previous attempt](https://github.com/google/gxui/pull/52#issuecomment-84957670).

I've added a new advanced sample - an open file dialog - which demonstrates the use of lists, trees and implementing their adapters.

Much of the delta of this PR is actually clean-up from the [previous PR](https://github.com/google/gxui/pull/52).

@crawshaw - what are your thoughts?

### CODE REVIEW

**Comment by sunwangme** [comment]
very good

**Comment by mattn** [comment]
Good. I want to use this example as standard library because I don't want to copy codes always I want this.
And I notice window class doesn't have `SetParent` to behave like `gtk_window_set_transient_for` in gtk.

**Comment by ben-clayton** [comment]
> I want to use this example as standard library because I don't want to copy codes always I want this.

Yeah, I've been thinking the same thing. I thought I'd throw this out there as a sample for now and maybe with a bit of cleanup we can make a composite component library.

> And I notice window class doesn't have SetParent to behave like gtk_window_set_transient_for in gtk.

Yeah, there's currently no built-in support for parenting windows. I'm not too sure what the desired set of features would be here. 
GLFW doesn't seem to support modal windows, not that I like them anyway.

**Comment by crawshaw** [comment]
I'm still wrapping my head around adapters, but LGTM.

**Comment by ben-clayton** [comment]
> I'm still wrapping my head around adapters, but LGTM.

Thanks.
They're loosely based on the [Adapters in android](http://developer.android.com/reference/android/widget/Adapter.html). I agree that the documentation needs more work.

**Comment by ben-clayton** [comment]
> I think you should specify how cheap or expensive the UI library expects these calls to be. If ItemAt is used in tight loops but ItemIndex is not, someone implementing an adapter should design for that.

I'm on the fence with this. It's not a particularly easy thing to state - "the UI library" could be anything. I'm certainly expecting controls to be developed that sit outside of the GXUI package. Hinting that one method is expected to be cheap while the other less-so might match the expectations of our current controls, but might not work well with future ones.
For the controls using Adapters inside GXUI, we need to be good citizens and reduce the number of calls to the Adapter to the absolute minimum required in order to function. They aren't too bad at the moment, but there could be more work done to improve this.

I'll have a think about this - you might be right in that ```ItemIndex``` is typically expected to be cheaper.

**Pull request merged**
