### PR TITLE
make default font the decision of the driver

### PR DESCRIPTION
**Pull request by crawshaw**
If we cannot find one, download a reasonable default from Google. The
URL will need to change in a few months when the project moves off
code.google.com, but so far it's the path we have.

Updates #13.

### CODE REVIEW

**Comment by crawshaw** [comment]
I'm not sure what googlebot is on about, my golang.org address is definitely on the Google CLA. (I'm a little reluctant to fill out the form through fear of breaking something. I'll send sop@ a message.)

cc @ben-clayton

**Comment by dskinner** [comment]
This is a slick idea but wouldn't it be more appropriate to query the system for a default font? On linux, the Fontconfig binary `fc-match` with no arguments will return a suitable default font, DejaVuSans.ttf in my case for example. I'd imagine OSX and Windows have similar facilities.

**Comment by crawshaw** [comment]
@dskinner agreed, the driver should do something cleverer. The download is just a 5-minute hack to make it easier for people to run samples. The main point of this CL is to shift the font decision to the driver.

My intention is to finish a driver I'm working on for golang.org/x/mobile/{app,gl,font}, which knows where android keeps its default, and knows how to query the system default on iOS.

**Comment by ben-clayton** [comment]
@dskinner I'm not so sure - one of the design goals of GXUI is that an application should appear identical on all OS's. I'm not keen on having the driver pick a OS specific font, as it will change all sorts of layout calculations.

**Comment by ben-clayton** [comment]
@crawshaw thanks - I'll take a look now.

**Comment by ben-clayton** [comment]
@dskinner I'm not sure I agree. If fitting in with the rest of the user's OS appearance was a goal, then we'd be using the native platform's windows, controls and widgets and this would result in a very different UI library.

For the good or bad, GXUI was designed to be cross platform in a way that means you don't have to spend time worrying about how it would look or behave on numerous other OS's. Things like switching fonts may seem minor, but in reality means that the whole UI needs to be manually tested for each target OS. If you want to do this with your application, that's fine - the API allows you to change fonts, but this is not something I want forced on every user of the library.

If you would like to have the ability to use the current desktop font in your GXUI application, then please file a request, and I'll see if we can add this to the soon-to-exist font package.

**Comment by dskinner** [comment]
You're right. My rationale falls into the case of designing a look-alike theme (something I have no interest personally in doing), so the functionality should be there. I'll file an issue.

**Comment by crawshaw** [comment]
Abandoning this in favor of #30 and #31.

**Pull request closed without merging**
