### PR TITLE
Add x/mobile/gl driver.

### LINKED ISSUE #45: x/mobile driver
It's not clear that GXUI will ever be ideal for mobile devices, but it's worth an experiment.

### PR DESCRIPTION
**Pull request by shurcooL**
This PR adds a second driver that uses `golang.org/x/mobile/gl` package. This package offers a slightly higher level interface, with desktop (OS X, Linux) and mobile (iOS, Android) backends. There is ongoing work to add support for Windows and web browsers.

Resolves #45.
Related to #49.

This is a large PR, I recommend looking at the 2 commits individually:

1. The first commit simply copies the `drivers/gl` package to `drivers/universalgl`, and renames the original `drivers/gl` to `drivers/desktopgl`. No logical changes here.

2. The second commit makes the necessary changes to `drivers/universalgl` to switch from using `github.com/go-gl/gl/v2.1/gl` to `golang.org/x/mobile/gl`. See commit message for detailed list of changes, and comments.

This PR depends on a couple changes/additions to the `golang.org/x/mobile/gl` package. I have created a CL for that, please see https://go-review.googlesource.com/#/c/8166/.

Please take a look, provide feedback, review.

### CODE REVIEW

**Comment by shurcooL** [comment]
Note, I don't necessary intend for this to be outright merged. It's more for review and discussion (with code you can look at), and to guide future development.

I think having 2 separate drivers that are nearly identical at this early stage of `gxui` is probably counter-productive, so after you are sufficiently happy with the new driver, I expect the original `desktopgl` to be simply replaced with `mobilegl.` That's why I didn't bother renaming the driver packages from `gl` to `desktopgl`, as I expect that to be a temporary import path.

**Comment by ben-clayton** [comment]
Hi @shurcooL 
[The changes](https://github.com/shurcooL/gxui/commit/34d32cd3bb185f280c53bbc215c6cefe42fc8473) to use ```mobile/gl``` look good. Thank you!
I'm not sure about the split in drivers though - this is really going to confuse people who are looking at this code for the first time. I think we should either:
* We wait until  ```mobile/gl``` covers the same support as the current driver (i.e. windows). And just switch the gl driver to use this. Or...
* We keep the current gl driver, and make [gl. StartDriver](https://github.com/google/gxui/blob/master/drivers/gl/driver.go#L33) return the ```universalgl``` driver for development and testing under a switch. However, I suspect this switch cannot be dynamic (i.e. a cmd line flag) due to two lots of conflicting CGO symbols, but I could be wrong.

@crawshaw do you have a feel for how much work there would be in getting ```mobile/gl``` to work on Windows? Perhaps this is something I could take a look at implementing.

**Comment by shurcooL** [comment]
Okay, https://go-review.googlesource.com/#/c/8166/ has been merged. There were a few changes, I'll need to update this PR (primarily, the GL_RED const was not added; instead I think it may make sense to use GL_LUMINOSITY for grayscale images, see [here](https://github.com/shurcooL/gxui/blob/34d32cd3bb185f280c53bbc215c6cefe42fc8473/drivers/universalgl/texture.go#L69-L71)).

I'll do that shortly.

Aside from that, it seems to merge this, we'd want to get the `x/mobile/gl` driver up to feature parity with the current desktop driver. The main missing feature is Windows support.

If the above is correct, then resolving https://github.com/golang/go/issues/9306 is next step for this PR to move forward.

**Comment by ben-clayton** [comment]
I'm not aware of anything using grayscale images. For now feel free to just pull that path.

**Comment by shurcooL** [comment]
Okay, I've removed the `image.Gray` support for now. It can always be re-added later when needed (using GL_LUMINOSITY instead of GL_RED).

I will rebase the PR, and also change it to just modify the existing `drivers/gl` rather than creating two `drivers/desktopgl` and `drivers/universalgl`, since that is the direction we are heading in. There will still be more work before it can be merged.

**Comment by shurcooL** [comment]
Actually, I'll make it a separate PR (since the entire original PR description is no longer valid).

**Comment by shurcooL** [comment]
Closing this in favor of #86.

**Pull request closed without merging**
