### PR TITLE
handle proper images

### PR DESCRIPTION
**Pull request by amitu**
This is better than the current garbage :-p

### CODE REVIEW

**Comment by amitu** [comment]
I have signed the CLA.

**Comment by ben-clayton** [comment]
Also, if you chose to roll your own image copy function instead of using the one in the [image/draw package](http://blog.golang.org/go-imagedraw-package) because of the flipped-y axis, you can use [Texture.SetFlipY](https://github.com/google/gxui/blob/master/texture.go#L16). 

As this is an example that will probably be copied (no pun intended), I would prefer it if we used [Draw](http://golang.org/pkg/image/draw/#Draw) unless there's a good reason not to.

Cheers,
Ben

**Comment by ben-clayton** [comment]
Accepting, and making the changes myself.

**Comment by amitu** [comment]
@ben-clayton thanks for accepting the patch.

I was not aware of the Texture.SetFlipY function.

Why do we have to use that? Why are we not fixing it internally? 

BMP is a legacy of past, it stores stuff upside down. Why does this library expect images upside down?

**Comment by ben-clayton** [comment]
> BMP is a legacy of past, it stores stuff upside down. Why does this library expect images upside down?
The reason isn't a good one, but is based around how GL expects the image data. You are correct though, it's broken on the public API where this really matters. I'll create a bug to get this fixed.

**Pull request merged**
