### PR TITLE
Update container.go

### PR DESCRIPTION
**Pull request by kre0n**

### CODE REVIEW

**Comment by dmitshur** [comment]
@kre0n, be aware of https://github.com/google/gxui/issues/166.

**Comment by ben-clayton** [comment]
The original code was correct, but admittedly it was not a great interface name. I don't think there's a PaintChildren type in the outer package, so I'm not sure how this compiles. 
Also, beware #166.

**Comment by dmitshur** [comment]
> I'm not sure how this compiles.

It doesn't:

```
# github.com/google/gxui/mixins/base
mixins/base/container.go:15: undefined: outer.PaintChildren
```

> The original code was correct, but admittedly it was not a great interface name.

I understand you were going with "{{Name}}er" formula for the interface name. A suggestion to consider is to apply the formula like https://godoc.org/io#Writer and https://godoc.org/io#WriterTo. Similarly, it could've been `outer.Painter` and `outer.PainterChild`. Or something.

**Comment by ben-clayton** [comment]
Yup, as I said, it wasn't a great interface name. :)

**Pull request closed without merging**
