### PR TITLE
Simplify the usage of Trees and add documentation.

### PR DESCRIPTION
**Pull request by ben-clayton**
@crawshaw - a continuation of the clean up of adapters - this time for Trees:

Kill TreeAdapter. Instead use Adapter and inspect the AdapterItems for compliance with the new TreeNode interface.
If the item complies with TreeNode, and has a count > 0, the item's control is made expandable.

This allows us to use the DefaultAdapter for Trees as well as Lists.

### CODE REVIEW

**Comment by crawshaw** [comment]
LGTM, that's definitely an improvement.

**Comment by ben-clayton** [comment]
I tried using this to build an open-file-dialog sample, and I'm starting to have serious doubts over this approach. Basically, [AdapterItem](https://github.com/google/gxui/blob/master/adapter.go#L13)s work great as POD types, not so great for more complex types, such as trees.

Let me explain why:

In the case of a directory tree view, it makes sense for the items (the data) to be absolute paths, so a string is the natural item type.
However, for expandable directories the item needs to implement the [TreeNode](https://github.com/google/gxui/blob/rm_treeadapter/tree.go#L43) interface, so we need to define a new type. The natural first thought is to declare a new type of string:
```go
type path string
```
But now the implementation of ```TreeNode``` now becomes very inefficient:
```go

func filesInPath(p path) []path { 
  /* some very expensive code that should not be called frequently */ 
}

func (p path) Count() int { return len(filesInPath(p)) }
func (p path) ItemAt(index int) AdapterItem { return filesInPath(p)[index] }
func (p path) ItemIndex(item AdapterItem) int { /* some complicated logic */ }
func (p path) Create(theme Theme, index int) Control { ... }
```

Worse still, this implementation is kind of broken - the file system could change at any moment, meaning indices could become invalid at any moment. So, we need some way to cache our view on the file system. Let's try again:

```go
type file struct {
  path string
  children []file
}

func (f file) Count() int { return len(f.children) }
func (f file) ItemAt(index int) AdapterItem { return f.children[index] }
func (f file) ItemIndex(item AdapterItem) int { /* some complicated logic */ }
func (f file) Create(theme Theme, index int) Control { ... }
```

Looks better - but this doesn't work. [AdapterItem](https://github.com/google/gxui/blob/master/adapter.go#L13)s *"must support equality and be hashable"*, which ```file``` now isn't because of the ```children []file``` field.
Okay, so, let's make the ```AdapterItem``` a pointer to the ```file```. The contract for ```AdapterItem``` is now good, but now it's impossible to use [Tree.Select](https://github.com/google/gxui/blob/master/tree.go#L22) without adding adapter traversal functions, as we can't trivially get the pointer to the ```file``` at the specified path. *sigh*

All of this has made me realise that this new [TreeNode](https://github.com/google/gxui/blob/rm_treeadapter/tree.go#L43) interface is on the wrong thing - [AdapterItem](https://github.com/google/gxui/blob/master/adapter.go#L13)s are the **data**. The [Adapter](https://github.com/google/gxui/blob/master/adapter.go#L18) is responsible for transforming that data into something that can be visualized, and this is where the methods of the  [TreeNode](https://github.com/google/gxui/blob/rm_treeadapter/tree.go#L43) interface belongs (just probably not with those signatures).

I'm still not happy with what's in master, but this approach doesn't seem any better.
Opinions, thoughts or suggestions are welcome on this.

**Comment by crawshaw** [comment]
Thinking very high level for a moment,

The idea behind Adapters is that the logic for drawing the UI element can be backed by any number of models. An alternative would be to invert responsibilities. Have one fixed, concrete data model for a UI element that an unknown-to-the-UI backing model is meant to update, that is:

```
type Node struct {
        Children []*Node
        Control // or something that represents the thing to draw
        ...
}
```

If each of these data model values is represented by a *T, then the pointer acts as a unique identifier. It is then the responsibility of any arbitrary data structure that is being visually represented to understand these concrete types and manipulate them. When the UI wants to change these types, the change instruction is encoded (e.g. Action{Delete, nodeValue}) and sent to the backing code that is responsible for keeping the model up to date.

So something like a file dialog ends up with two models:

*fileNode -> *Node -> UI

(This is just a random idea. It's not even clear to me that it would work.)

**Comment by dskinner** [comment]
One approach I'm working on - on android - is to treat adapters as containing collated sets. So typically for large lists, there may be a db cursor containing a relevant data set. There may then be additional requirements for the display of the list including things like grouping headers, unique position views inlined, repetitive views not necessarily related to the cursor data itself located at offsets, etc.

The next step to that is to collate multiple cursors which is useful for expand and collapse of additional inlined data (tree view) and other currently unidentified scenarios.

I think the key word here is *inlined* since the adapter is effectively about maintaining a flat list of items even though such items might be visually represented otherwise.

This would make the responsibilities of the adapter the following:

* Determine true length of collated sets and any defined affixables as a single flat list
* Determine control type at a given offset and be able to retrieve the correct (if relevant) data (such as moving a cursor to the correct position to pass on during binding)
* Facilitate control binding (assuming adapter controls implemented something like `type Binder interface { Bind() }`)

Of course the last point isn't addressed very well in Go for binding from a specific set.

Really, as long as the base adapter is general enough, all of this doesn't need to be written to write a tree view and could exist in a 3rd party lib, but I think a robust set of features similar to the above would facilitate things like a Tree view and even allow for variations on the Tree with minimal additional work while also facilitating lots of other possibilities for displaying various lists.

**Comment by ben-clayton** [comment]
Closing in favour of [the second attempt](https://github.com/google/gxui/pull/63).

**Pull request closed without merging**
